### ISSUE TITLE
Cordova 6.0?

### ISSUE THREAD

**Issue by geppy** [localytics/localytics-cordova#10]
I've just added this to a Cordova 6.0 project.   I've set up the key (`getAppKey` returns the right result), but the tracking data isn't showing up.

**Comment by blinder** [comment]
Noticing the same thing. It isn't sending session data, and i've created several event tags, none of them are showing up. i was digging around the source and noticed there are callbacks for success and failure, and none of them are called either. It's as if Localytics is just not there. 

i'm guessing Cordova is just not a thing Localytics has any interest in supporting.

**Comment by ysamlan** [comment]
We'll be publishing a Cordova 6 compatibility update in the next week or two. We are actively supporting our Cordova SDK, but we've been busy at work on an update to our core iOS and Android SDKs so we went a little radio silent over here - sorry!

**Comment by ysamlan** [comment]
Our Cordova 6 / SDK 3.8 release went out in early June - let us know if you this doesn't solve your problem.
