### ISSUE TITLE
Places / Location Monitoring

### ISSUE THREAD

**Issue by NickMele** [localytics/localytics-cordova#13]
I was wondering if there were plans on adding the location monitoring that can be used for the new places functionality into this plugin. I understand that is was just released and can take some time to get updated, but just wanted to know if it was in the pipeline for the near future.

Thanks, and awesome work on the plugin!

**Comment by ysamlan** [comment]
Thanks for asking - we're planning to update the wrapper to include SDK 4.0 functionality, including Places, later this year. I don't have a hard date to share on that at the moment, but if this is for a particular Localytics Enterprise account, please reach out to your account manager and let them know you're looking for this functionality in our Cordova plugin.

**Comment by NickMele** [comment]
Thank you for responding so quickly. Unfortunately we do not, yet, have an enterprise account. Hopefully we will see this feature soon though since its a pretty important business requirement for us.

**Comment by abashyam** [comment]
Closing this issue as it has been addressed in a plugin update already
