### ISSUE TITLE
Documentation outdated? ClassNotFoundException: com.google.android.gms.gcm.GoogleCloudMessaging

### ISSUE THREAD

**Issue by yves-s** [localytics/localytics-cordova#14]
As you say in step [3 - Android](https://github.com/localytics/localytics-cordova#android-2) adding the whole google-play-services_lib isn't recommended anymore and you won't find the lib on the given location. I fixed the issue by adding `<framework src="com.google.android.gms:play-services-gcm:8.4.0" />` to the `<platform name="android"></platform>` section on the localytics-cordova plugins.xml.

**Comment by deRonbrown** [comment]
@yves-s Do you mind submitting a PR to update the REAME?

**Comment by yves-s** [comment]
Sure @deRonbrown , will do that. I think latest Monday

**Comment by yves-s** [comment]
Ok, I just noticed you don't have to add the framework line mentioned above, it's already added to the plugin.xml. So I will only delete the unnecessary passage. It's also worth to mention that loading a framework with "+" as the version indicator could lead to issues if you use different plugins or updated the sdk.

**Comment by yves-s** [comment]
Referenced to: **Removed unnecessary section about copying the google-play-services_lib** #15

**Comment by abashyam** [comment]
No updates on this issue and the autoIntegrate issue has been resolved. closing this. Open a new issue if you still have an outstanding issue.
