### ISSUE TITLE
Multiple push providers on iOS failing to register

### ISSUE THREAD

**Issue by eneskaya** [localytics/localytics-cordova#17]
In our app, we want to use Localytics SDK along with another push provider. But when the other SDK is enabled, the Localytics event "Localytics Push Registered" is not sent anymore. What can I do to fix this? The complete migration to Localytics is not yet possible.

**Comment by ysamlan** [comment]
Totally understand the need here - in our native SDKs we expose some extra hooks (http://docs.localytics.com/dev/android.html#custom-push-configuration-android) to allow configurability with multiple push providers by allowing customers to pass push tokens directly, which allows customers to self-register for push and work around these sorts of limitations in other push SDKs. We currently have support for those extra hooks planned for our Localytics Cordova SDK 4.0 update later this year.

**Comment by abashyam** [comment]
With the latest SDK use setPushToken to configure the push token and you should be able to send Pushes.
