### ISSUE TITLE
libLocalytic version in this plugin is outdated

### ISSUE THREAD

**Issue by dozoisch** [localytics/localytics-cordova#2]
Is it possible to update to 3.5.1 (instead of current 3.4.0) in order to have the bitcode support added in 3.5.1?

**Comment by berndartmueller** [comment]
+1

**Comment by ArtKuz** [comment]
+1

**Comment by dozoisch** [comment]
@lewong any updates on this?

**Comment by ysamlan** [comment]
We'll be releasing a Cordova 6 update that includes an update to Localytics SDK 3.8 in the next few weeks.

**Comment by ysamlan** [comment]
We released our update in early June with SDK 3.8 - let us know if you have other issues.
