### ISSUE TITLE
Receive custom data from campaign -> creatives section

### ISSUE THREAD

**Issue by yves-s** [localytics/localytics-cordova#21]
With another push provider it is possible to listen to 'push-notification' (`document.addEventListener('push-notification', callback);`) and receive and handle custom data.

With Localytics I didn't find any solution to handle this.

Is there any possibility I didn't find?

**Comment by ysamlan** [comment]
Localytics wires into Cordova's CDVPlugin appdelegate methods for handling pushes on iOS. To override that handling today I believe you'd have to drop down to native code and hook into the appdelegate directly, or write your own push receiver for Android. You can see the iOS code here:
https://github.com/localytics/localytics-cordova/blob/master/src/ios/LocalyticsPlugin.m#L54

On Android, all the extra K/Vs on the push are passed through on the Intent extras when your app is opened; you may need to use a plugin such as https://github.com/napolitano/cordova-plugin-intent to access those.

**Comment by abashyam** [comment]
closing this issue. There has not been any activity in a while.
