### ISSUE TITLE
Any plan to update to SDK v4?

### ISSUE THREAD

**Issue by massivekarenwong** [localytics/localytics-cordova#26]
Deeplinking from push notifications and the new rapid push notifications verification both require higher SDK version than the version that this plugin currently supported. Is there any plan to upgrade the SDK version to 4.1.0 or higher to support both? Thanks!

**Comment by william-beange-hs** [comment]
There is a PR open with upgraded SDK. Have you tried testing it at all? https://github.com/localytics/localytics-cordova/pull/23

**Comment by abashyam** [comment]
Localytics has updated Cordova to SDK 5.1. Closing this issue.
