### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by berndartmueller** [localytics/localytics-cordova#5]
Hello,

I'm currently trying to integrate localytics in my Ionic/Cordova project but building does not work. 
Cordova version is 5.1.1 and cordova ios platform version is 3.8.0

Can someone please help?

Undefined symbols for architecture i386:
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[CDVReachability reachabilityWithAddress:] in CDVReachability.o
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[CDVReachability reachabilityWithHostName:] in CDVReachability.o
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
      -[TAGNetReachability start] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      ___49-[LLInAppManager ampMessageDictionaryForResults:]_block_invoke in libLocalytics.a(LLInAppManager.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[CDVReachability connectionRequired] in CDVReachability.o
      -[CDVReachability currentReachabilityStatus] in CDVReachability.o
      ___49-[LLInAppManager ampMessageDictionaryForResults:]_block_invoke in libLocalytics.a(LLInAppManager.o)
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[CDVReachability startNotifier] in CDVReachability.o
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
      -[TAGNetReachability start] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[CDVReachability startNotifier] in CDVReachability.o
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
      -[TAGNetReachability start] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      -[TAGNetReachability stop] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[CDVReachability stopNotifier] in CDVReachability.o
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
      -[TAGNetReachability stop] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
  "_crc32", referenced from:
      _ll_unzReadCurrentFile in libLocalytics.a(ll_unzip.o)
  "_deflate", referenced from:
      +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] in libGoogleAnalyticsServices.a(GAICompressionUtil.o)
      -[GCDWebServerGZipEncoder readData:] in GCDWebServer(GCDWebServerResponse.o)
      -[LLAnalyticsUploader gzipDeflatedDataWithData:] in libLocalytics.a(LLAnalyticsUploader.o)
  "_deflateEnd", referenced from:
      +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] in libGoogleAnalyticsServices.a(GAICompressionUtil.o)
      -[GCDWebServerGZipDecoder open:] in GCDWebServer(GCDWebServerRequest.o)
      -[GCDWebServerGZipEncoder open:] in GCDWebServer(GCDWebServerResponse.o)
      -[GCDWebServerGZipEncoder close] in GCDWebServer(GCDWebServerResponse.o)
      -[LLAnalyticsUploader gzipDeflatedDataWithData:] in libLocalytics.a(LLAnalyticsUploader.o)
  "_deflateInit2_", referenced from:
      +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] in libGoogleAnalyticsServices.a(GAICompressionUtil.o)
      -[GCDWebServerGZipEncoder open:] in GCDWebServer(GCDWebServerResponse.o)
      -[LLAnalyticsUploader gzipDeflatedDataWithData:] in libLocalytics.a(LLAnalyticsUploader.o)
  "_inflate", referenced from:
      +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libGoogleAnalyticsServices.a(GAICompressionUtil.o)
      -[GCDWebServerGZipDecoder writeData:error:] in GCDWebServer(GCDWebServerRequest.o)
      _ll_unzReadCurrentFile in libLocalytics.a(ll_unzip.o)
  "_inflateEnd", referenced from:
      +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libGoogleAnalyticsServices.a(GAICompressionUtil.o)
      -[GCDWebServerGZipDecoder close:] in GCDWebServer(GCDWebServerRequest.o)
      _ll_unzCloseCurrentFile in libLocalytics.a(ll_unzip.o)
  "_inflateInit2_", referenced from:
      +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libGoogleAnalyticsServices.a(GAICompressionUtil.o)
      -[GCDWebServerGZipDecoder open:] in GCDWebServer(GCDWebServerRequest.o)
      _ll_unzOpenCurrentFile3 in libLocalytics.a(ll_unzip.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

**Comment by berndartmueller** [comment]
I was able to get it work by manually adding CFNetwork.framework and libz.tbd to XCode Build Phases, but those frameworks are not added when installing the plugin. 

Somehow <framework src="libz.tbd" /> and <framework src="CFNetwork.framework" /> do not work.

Any ideas?

**Comment by abashyam** [comment]
Localytics Cordova SDK 5.1 has been released and the issue no longer exists. If you see unexpected behavior open an issue.
